<a href="https://colab.research.google.com/github/Red-Rose-AI/Learn_Numpy_by_solving_problems/blob/main/Learn_Numpy_By_Solving_Problem_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# <font color='red'>------------||  Red Rose AI  ||------------</font>

---


**Empowering AI Enthusiasts: Theory to Practice with Red Rose AI**


---



**Problem 4:** Create a NumPy array called ones_array with a shape of (3, 4) filled with ones. Print the array.


In [ ]:
import numpy as np

In [ ]:
ones_list = [1 for i in range(3*4)]
print('ones list: ', ones_list)
print('length of list: ', len(ones_list))

ones list:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
length of list:  12


In [ ]:
ones_list = [1] * (3*4)
print('ones list: ', ones_list)
print('length of list: ', len(ones_list))

ones list:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
length of list:  12


In [ ]:
ones_array = np.array(ones_list)
print('ones array: ', ones_array)
print('type: ', type(ones_array))

ones array:  [1 1 1 1 1 1 1 1 1 1 1 1]
type:  <class 'numpy.ndarray'>


In [ ]:
# reshape
ones_array = np.array(ones_list).reshape((3, 4))
print('ones array: \n', ones_array)
print('type: ', type(ones_array))
print('shape: ', ones_array.shape)

ones array: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
type:  <class 'numpy.ndarray'>
shape:  (3, 4)


In [ ]:
#np.ones
ones_array = np.ones((3, 4), dtype=np.int32)
print('ones array: \n', ones_array)
print('type: ', type(ones_array))
print('shape: ', ones_array.shape)
print('data type: ', ones_array.dtype)

ones array: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
type:  <class 'numpy.ndarray'>
shape:  (3, 4)
data type:  int32


In [ ]:
np.ones((10,), dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
# reshape
ones_array = np.array(ones_list).reshape((3, 5))
print('ones array: \n', ones_array)
print('type: ', type(ones_array))
print('shape: ', ones_array.shape)

ValueError: ignored