<a href="https://colab.research.google.com/github/Red-Rose-AI/Learn_Numpy_by_solving_problems/blob/main/Learn_Numpy_By_Solving_Problem_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# <font color='red'>------------||  Red Rose AI  ||------------</font>

---


**Empowering AI Enthusiasts: Theory to Practice with Red Rose AI**


---



**Problem 5:** Create a NumPy array called identity_matrix with a shape of (4, 4) representing an identity matrix. Print the array.

- An identity matrix is a given square matrix of any order which contains on its main diagonal elements with value of one, while the rest of the matrix elements are equal to zero.

      `
      [[1, 0, 0, 0],

       [0, 1, 0, 0],

       [0, 0, 1, 0],

       [0, 0, 0, 1]]
       `

In [ ]:
import numpy as np

In [ ]:
identity_list = []
for i in range(4):
  for j in range(4):
    if i == j:
      identity_list.append(1)
    else:
      identity_list.append(0)

print('identity list: ', identity_list)

identity list:  [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]


In [ ]:
identity_array = np.array(identity_list)
print('identity array: ', identity_array)
print('shape: ', identity_array.shape)


identity array:  [1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]
shape:  (16,)


In [ ]:
identity_matrix = identity_array.reshape((4, 4))
print('identity matrix: \n', identity_matrix)
print('shape: ', identity_matrix.shape)


identity matrix: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
shape:  (4, 4)


In [ ]:
# np.identity
identity_matrix = np.identity(4, dtype=np.int32)
print('identity matrix: \n', identity_matrix)
print('shape: ', identity_matrix.shape)

identity matrix: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
shape:  (4, 4)
